services:
  db:
    build: ./DB
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
  front:
    image: front
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - db
  backend:
    image: backend
    build:
      context: ./Backend
    ports:
      - "4000:4000"
      - "5555:5555"
    depends_on:
      - db
      - front
    volumes:
      - upload-vol:/app/uploads
     

volumes:
  db-data:
  upload-vol: